version: "3.9"

services:

  devops:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: soc-devops

    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws

    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

    working_dir: /workspace

    tty: true