version: "3.9"

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.9.0
    container_name: wazuh-indexer
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - wazuh_indexer_data:/var/lib/wazuh-indexer
    ports:
      - "9200:9200"

  wazuh-manager:
    image: wazuh/wazuh-manager:4.9.0
    container_name: wazuh-manager
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh_manager_data:/var/ossec/data
      - ./automation:/var/ossec/integrations/custom
      - ./ossec.conf:/var/ossec/etc/ossec.conf:ro
      - ./rules:/var/ossec/etc/rules:ro

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    container_name: wazuh-dashboard
    environment:
      - WAZUH_INDEXER_URL=https://wazuh-indexer:9200
    ports:
      - "443:443"
    depends_on:
      - wazuh-indexer

volumes:
  wazuh_indexer_data:
  wazuh_manager_data:

