- name: Configure Victim server
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    wazuh_manager_ip: "{{ wazuh_manager_ip | default('127.0.0.1') }}"
    aws_region: "{{ aws_region | default('eu-north-1') }}"
    ecr_victim_repository_url: "{{ ecr_victim_repository_url | default('') }}"
  roles:
    - victim_server
